# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170612_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AddField(
            model_name='about',
            name='about_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
