# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170612_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ManyToManyField(to='mainapp.Category'),
        ),
    ]
