# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170612_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='category',
            new_name='categories',
        ),
    ]
